#pragma once
#include"CShape.h"

/*нд╠╬*/
SHAPE_CLASS_START(CText, SHAPE_PROPERTY_TEXT, SHAPE_PROPERTY_HEIGHT, SHAPE_PROPERTY_ANGLE)
protected:
	RECT rect;
	SHAPE_PROPERTY_TEXT;
	SHAPE_PROPERTY_HEIGHT;
	SHAPE_PROPERTY_ANGLE;
SHAPE_CLASS_END